###get all the product details
GET http://localhost:3000/products-api/products

###insert new product details
POSt http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productID":200,
    "Product Name":"mobile",
    "cost":5000
}


###get product details by id
GET http://localhost:3000/products-api/product/200


###update product details vy id
PUT http://localhost:3000/products-api/products/id
Content-Type: application/json

{
    "productID":200,
    "Product Name":"computer",
    "cost":123
}

###delete product by id
DELETE http://localhost:3000/products-api/products/200

